### ISSUE TITLE
Device Proxy Timeout is overwritten after a re-connection

### ISSUE THREAD

**Issue by faranguiss-poncet** [tango-controls/JTango#100]
Hello,
In a Java Client when a device proxy timeout is set to a specific value (different from the default 3000 ms) ,
if the connection to the device server is lost for whatever the reason, the Tango automatic re-connection,
overwrites the device proxy timeout and sets it to the default value = 3000 ms.

We are using JTango-9.5.15.

Could you please fix this bug?
Thanks,
Faranguiss

**Comment by Pascal-Verdier** [comment]
Problem fixed in files:
- dao/src/main/java/fr/esrf/TangoApi/ConnectionDAODefaultImpl.java
- dao/src/main/java/fr/esrf/TangoApi/DeviceProxyDAODefaultImpl.java

Will be available in next JTango release.
Pascal
