### ISSUE TITLE
New release for tango source distribution

### ISSUE THREAD

**Issue by t-b** [tango-controls/JTango#101]
It would be nice to get a new release so that we can include JTango with the Java11 fix in the tango source distribution.

**Comment by t-b** [comment]
@gwen-soleil With which java versions will https://github.com/tango-controls/JTango/releases/tag/9.6.0 be compatible? With 11 or above? Or even with 8?

**Comment by gwen-soleil** [comment]
Yes, it is compiled with java 8 and works with java 8 and above

**Comment by t-b** [comment]
@gwen-soleil Thanks for the new release.
