### ISSUE TITLE
Random TimeoutExceptions in java client (TangORB)

### ISSUE THREAD

**Issue by tango-controls-bot** [tango-controls/JTango#19]
In our case we have Java client and a server. Client polls server for a command every 10 ms in a loop. Sometimes this can run smoothly for up to 3 hours, sometimes only 15 minutes. But normally client crashes after ~1h with a timeout exception. We tried with TangORB-8.4.2 and 9.0.1 (both from the soleil's maven repo). Below is some additional information. Suggested workaround patch is attached.

>
> In my test case server is running on debian 7:
>
> Linux hzgpp07ctrec2 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
> 
> Java version:
> 
> java version "1.8.0_25"
> Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
> Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
> 
> in a server mode, i.e. was launched with -server java param.
> 
> Client is on Windows 7 with java version:
> 
> java version "1.8.0_05"
> Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
> 

Here is some log output:

> [main] INFO org.jacorb.orb - Initialising ORB with ID:
> [main] INFO org.jacorb.orb.giop - ClientConnectionManager: created new  ClientGIOPConnection to 131.169.65.104:10000 (6b927fb)
> [main] INFO org.jacorb.orb.iiop.ClientIIOPConnection - Connected to 131.169.65.104:10000 from local port 56378
> [main] INFO org.jacorb.orb.giop - ClientConnectionManager: created new ClientGIOPConnection to 131.169.65.240:39478 (477b4cdf)
> [main] INFO org.jacorb.orb.iiop.ClientIIOPConnection - Connected to 131.169.65.240:39478 from local port 56379
> [ClientMessageReceptor0] INFO org.jacorb.giop.conn - Received CloseConnection on ClientGIOPConnection to 131.169.65.104:10000 (6b927fb)
> [ClientMessageReceptor0] INFO org.jacorb.orb.iiop.ClientIIOPConnection - Client-side TCP transport to 131.169.65.104:10000 closed.
> [main] WARN org.jacorb.giop.conn - Abnormal connection termination. Lost 1 outstanding replie(s)!
> [main] INFO org.jacorb.orb.iiop.ClientIIOPConnection - Client-side TCP transport to 131.169.65.240:39478 closed.
> [main] ERROR org.tango.client.ez.proxy.DeviceProxyWrapper - DeviceProxyWrapper#executeCommand has failed.
>

Looks like jacorb randomly closes underlying connection:
> [main] WARN org.jacorb.giop.conn - Abnormal connection termination. Lost 1 outstanding replie(s)!

And if the client is so unlucky that it is awaiting a response in this moment it crashes with the timeout exception.

Reported by: Ingvord ( http://sf.net/u/ingvord )

Original Ticket: [tango-cs/bugs/710](https://sourceforge.net/p/tango-cs/bugs/710)

**Comment by Ingvord** [comment]
Some more info on this issue

Seems that problem occurs in [`org.tango.orbServerRequestInterceptor.java#85`](https://github.com/tango-controls/JTango/blob/14a6527e3ca67339e51a905ef6c55d773ed04cb7/server/src/main/java/org/tango/orb/ServerRequestInterceptor.java#L85)

Namely the `RequestProcessor` thread goes to sleep at that line for 5s:

```
DEBUG 10-12-2019 12:29:15.042 [RequestProcessor-4 - o.j.o.p.AbstractInterceptorIterator] invoke( org.tango.orb.ServerRequestInterceptor )
TRACE 10-12-2019 12:29:15.042 [RequestProcessor-4 - o.t.o.ServerRequestInterceptor] infoImpl.getConnection().getTransport()
TRACE 10-12-2019 12:29:15.042 [RequestProcessor-4 - o.t.o.ServerRequestInterceptor] connex.getSocket()
TRACE 10-12-2019 12:29:15.042 [RequestProcessor-4 - o.t.o.ServerRequestInterceptor] clientIPAddress.set(sock.getInetAddress().getHostAddress())
TRACE 10-12-2019 12:29:15.042 [RequestProcessor-4 - o.t.o.ServerRequestInterceptor] sock.getPort()
TRACE 10-12-2019 12:29:15.042 [RequestProcessor-4 - o.t.o.ServerRequestInterceptor] InetAddress.getByName(clientIPAddress.get()).getCanonicalHostName()
!!!5s delay!!!
TRACE 10-12-2019 12:29:20.047 [RequestProcessor-4 - o.t.o.ServerRequestInterceptor] giopHostAddress.set(GIOP_TCP + clientIPAddress.get() + ":" + remotePort)
DEBUG 10-12-2019 12:29:20.047 [RequestProcessor-4 - o.j.o.p.AbstractInterceptorIterator] invoke( org.tango.orb.ServerRequestInterceptor ) done
```

**Comment by Ingvord** [comment]
I have decomposed line 85 and here is the output:

```
DEBUG 10-12-2019 13:00:06.282 [RequestProcessor-5 - o.j.o.p.AbstractInterceptorIterator] invoke( org.tango.orb.ServerRequestInterceptor )
TRACE 10-12-2019 13:00:06.282 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] infoImpl.getConnection().getTransport()
TRACE 10-12-2019 13:00:06.282 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] connex.getSocket()
TRACE 10-12-2019 13:00:06.282 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] clientIPAddress.set(sock.getInetAddress().getHostAddress())
TRACE 10-12-2019 13:00:06.283 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] sock.getPort()
TRACE 10-12-2019 13:00:06.283 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] InetAddress.getByName(clientIPAddress.get()).getCanonicalHostName()
TRACE 10-12-2019 13:00:06.283 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] clientIPAddress.get()
TRACE 10-12-2019 13:00:06.283 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] clientIPAddress.get() done: 131.169.65.104
TRACE 10-12-2019 13:00:06.283 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] InetAddress.getByName(clientIpAddress)
TRACE 10-12-2019 13:00:06.283 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] InetAddress.getByName(clientIpAddress) done: /131.169.65.104
TRACE 10-12-2019 13:00:06.283 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] clientInetAddress.getCanonicalHostName()
!!! 5s delay !!!
TRACE 10-12-2019 13:00:11.288 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] clientInetAddress.getCanonicalHostName() done: hzgc103k.desy.de
TRACE 10-12-2019 13:00:11.288 [RequestProcessor-5 - o.t.o.ServerRequestInterceptor] giopHostAddress.set(GIOP_TCP + clientIPAddress.get() + ":" + remotePort)
DEBUG 10-12-2019 13:00:11.288 [RequestProcessor-5 - o.j.o.p.AbstractInterceptorIterator] invoke( org.tango.orb.ServerRequestInterceptor ) done
```

**Comment by bourtemb** [comment]
This might be related to the network configuration.
I remember we faced something like that in the past and the solution we found was to run nscd daemons on our hosts to cache dns queries.
We had also some issues in our /etc/hosts files where we had to to comment out a line (maybe not linked to this issue):

```
234.456.789.1 myhost.mydomain.org myhost
# Commented because of Java.
# InetAddress.getLocalHost().getHostAddress() returns the FIRST IP in the list
# but the list is sorted by IP... so 127.0.1.1 is always returned (234> 127)
# 127.0.1.1 myhost.mydomain.org myhost
```

**Comment by bourtemb** [comment]
We also had an issue once with our DNS configuration where 192.168.0.0 requests were forwarded to CISCO appliances when they should not have been.
We were observing these 5s timeouts too at that time.

**Comment by Ingvord** [comment]
Well, that seems to be a quite well known issue with `getCannonicalHostName()` method from JDK

Just google "getCanonicalHostName() 5s delay"

The problem is that we do not want to reconfigure network here at DESY, 'cause in my understanding that means to hardcode all known hosts for each beamline in `/etc/hosts`

**Comment by Ingvord** [comment]
I wonder if this is the only reason for random timeouts...

**Comment by Ingvord** [comment]
With patch from #98 the problem seems to be solved...

At least simple code snippet like:

```java
    @Test
    @Ignore
    public void testTimeoutAttribute() throws Exception{
        TangoAttribute attr = new TangoAttribute("development/test_server/0/testTimeoutAttribute");

        for(long i = 0; i<1_000_000; ++i) {
            long start = System.currentTimeMillis();

            String result = null;
            try {
                result = attr.read(String.class);
                System.out.println(String.format("%d\t%d\t%s\t%d",i,start,result, System.currentTimeMillis()));
            } catch (CommunicationTimeout timeout) {
                System.out.println(String.format("%d\t%d\ttimeout!!!\t%d",i,start,System.currentTimeMillis()));
                throw timeout;
            }

        }
    }
```

worked for 6hrs without any timeouts
