### ISSUE TITLE
Methods have disappeared in DeviceProxy class

### ISSUE THREAD

**Issue by Pascal-Verdier** [tango-controls/JTango#49]
2 methods **writeReadPipe** available on **DeviceProxy** class since last year on sourceforge, do not exist any more in **JTango**  source files today.

**Comment by Ingvord** [comment]
Probably a side of effect of migration. Can you bring them back, please?

**Comment by Pascal-Verdier** [comment]
Yes I can and I will.
But I am afraid that other updateS between this migration and the official migration done, will missing.

**Comment by Pascal-Verdier** [comment]
I did it on master for **DeviceProxy.java** and **IDeviceProxyDAO.java** files.

**Comment by Ingvord** [comment]
Yeah, unfortunately JTango migration took ~1/2 year so it might be some other stuff is missing even though I synchronized it.

**Comment by Ingvord** [comment]
Close due to 181fe08
