### ISSUE TITLE
Latest JTango release 9.5.10 is missing from bintray's generic repo

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/JTango#61]
i.e. fat jar is not available: [link](https://bintray.com/tango-controls/generic/JTango-9-LTS)

**Comment by gwen-soleil** [comment]
Hello Igor,

I don't know what went wrong during release. I have followed the procedure: https://github.com/tango-controls/JTango/wiki. Shall I do a new release?

**Comment by Ingvord** [comment]
@gwen-soleil , the most obvious thing that comes into my mind is that `bintray.user.name` and `bintray.user.apikey` are missing during upload, maven log should say something about that. Please make sure you have your settings.xml set properly:

```xml
<activeProfiles>
        <activeProfile>bintray</activeProfile>
    </activeProfiles>
<profiles>
        <profile>
            <id>bintray</id>
            <activation>
                <property>
                    <name>release</name>
                </property>
            </activation>
            <properties>
                <bintray.user.name>YOUR_BINTRAY_USERNAME</bintray.user.name>
                <bintray.user.apikey>YOUR_BINTRAY_APIKEY</bintray.user.apikey>
            </properties>

        </profile>
</profiles>
```

You can either upload the file manually, or, even better, do a new release - to check if it works fine.  Thanks!

**Comment by gwen-soleil** [comment]
Tried with a new release,  still not working. Moreover, I have lost track of the maven logs. So I am not able to send you the error messages.
I have uploaded it manually.
