### ISSUE TITLE
Latest JTango release 9.5.10 is not synced with maven central

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/JTango#62]
for instance [JTangoCommons](https://mvnrepository.com/artifact/org.tango-controls/JTangoCommons)

**Comment by gwen-soleil** [comment]
I have tried without success. I have an error:

403 - Forbidden
User 'gwen-soleil' missing 'stage' permission for staging profile: 

Could not sync artifact JTangoCommons-9.5.11.jar.md5. Server response:

**Comment by gwen-soleil** [comment]
By the way, isn't possible to configure travis to deploy automatically to bintray and maven central?

**Comment by Ingvord** [comment]
@gwen-soleil you need to create a user at sonartype and associate it with org.tango-controls repo at maven central: 

Follow [this link](https://issues.sonatype.org/browse/OSSRH-30894?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)

Create a user and add a ticket to JIRA "please authorize my user to publish to org.tango-controls". Hope that would do the trick :)

We can auto-deploy fat-jar to bintray (or even better - I would switch to GitHub releases) with travis, if travis would do release (for instance for tagged commits). I do not know whether we can sync with maven central though... should be possible but may require quite a lot of efforts to setup this.

**Comment by Ingvord** [comment]
I wanted to sync with maven central myself and noticed that JTango is missing from bintray/'s maven: there is no 9.5.10 version at all. And 9.5.11 is missing pom files: [link](https://bintray.com/tango-controls/jtango/JTango/9.5.11#files/org/tango-controls/JTango). So definitely maven release was screwed up

**Comment by Ingvord** [comment]
@gwen-soleil , So I would suggest to perform next release together to find out what is the problem and solve it.

**Comment by gwen-soleil** [comment]
thanks for helping. I hope to see u at next tango developers' meeting :)

**Comment by Ingvord** [comment]
Closed due to #73
