### ISSUE TITLE
Automatize release procedure

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/JTango#68]
- [x] replace maven release plugin with build-verions etc as in SOLEIL (@gwen-soleil , could you please provide the execution command line you use to release at SOLEIL)
- [x] setup Travis so that it performs release when repo is tagged
- [x] attach fat jar to GitHub releases rather than upload it to bintray

**Comment by gwen-soleil** [comment]
What we use at SOLEIL with jenkins and SVN:
`build-helper:parse-version versions:set -DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}-${SVN_REVISION}${parsedVersion.qualifier} -DautoVersionSubmodules=true`

**Comment by Ingvord** [comment]
@gwen-soleil , thanks a lot!

**Comment by gwen-soleil** [comment]
Hi Igor,

Here is a documentation to deploy from travis to bintray:
https://docs.travis-ci.com/user/deployment/bintray/
https://github.com/bintray/bintray-examples/tree/master/travis-ci-example

From my point of view, the best solution would be to deploy automatically into bintray each time a git tag is done.

**Comment by Ingvord** [comment]
@gwen-soleil , Sure that is one of the goals:

> setup Travis so that it performs release when repo is tagged

**Comment by Ingvord** [comment]
@gwen-soleil ,
@bourtemb ,
@Pascal-Verdier 

Just for your information I have updated the wiki release section according to this issue:

https://github.com/tango-controls/JTango/wiki#how-to-release
