### ISSUE TITLE
Heartbeat errors when using TangoBox9.3-aws

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/JTango#89]
Hi,

I just downloaded TangoBox-9.3-aws.ova and I played a bit with it.
I noticed that I'm getting hearbeat error events when I run an atkpanel on sys/tg_test/1 (TangoTest device) on the attributes which are polled.
I noticed I didn't get this kind of errors with the archiving/hdbpp/eventsubscriber.1 device, which is using the same Tango C++ library.
I don't get any error when using a 9.3.3 C++ client subscribing to periodic events on the sys/tg_test/1  polled attributes.

I suspect an issue with JTango when connecting to device servers running on hosts having several network interfaces or with funny network configurations when using docker...

This seems to be confirmed with the fact that when moving TangoTest/test instance to tangobox-hdbpp "host", which has only one network interface, there is no heartbeat error any more (I restarted a new atkpanel to start from a clean situation after the move of device server).

I tried with latest version of JTango 9.5.17 and I got the same error.

**Comment by gwen-soleil** [comment]
Hi @bourtemb ,

Could you do the test with the release https://github.com/tango-controls/JTango/releases/tag/9.6.6? It is still reproducible?

**Comment by bourtemb** [comment]
> Hi @bourtemb ,
> 
> Could you do the test with the release https://github.com/tango-controls/JTango/releases/tag/9.6.6? It is still reproducible?

Hi @gwen-soleil , I don't even manage to reproduce it with the old JTango version provided with the latest TangoBox-9.3-aws (the [one published on 19th September 2019](https://s2innovation.sharepoint.com/sites/Developers/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FDevelopers%2FShared%20Documents%2FTangoBox%2F9%2E3&p=true&originalPath=aHR0cHM6Ly9zMmlubm92YXRpb24uc2hhcmVwb2ludC5jb20vOmY6L3MvRGV2ZWxvcGVycy9Fb3ZEMklCd2hwcEFwLVpMWHRhd1E2Z0I5RjZhWFBQczJtc3IyaGdQR1RPLUZRP3J0aW1lPUcxelpHWlJqMkVn))

So I think we can close this issue.
