### ISSUE TITLE
Broken transitive dependency on nanocontainer-remoting:1.0-RC-1

### ISSUE THREAD

**Issue by altavir** [tango-controls/JTango#91]
Gradle build fails with 
```
 Could not resolve nanocontainer:nanocontainer-remoting:1.0-RC-1.
     Required by:
         project : > org.jacorb:jacorb-services:3.9
      > Could not resolve nanocontainer:nanocontainer-remoting:1.0-RC-1.
         > inconsistent module metadata found. Descriptor: nanocontainer-remoting:nanocontainer-remoting:1.0-RC-1 Errors: bad group: expected='nanocontainer' found='nanocontainer-remoting'
```
It seems that POM file is broken on `nanocontainer-remoting`. Maven probably ignores it, but gradle is failing on that.

**Comment by Ingvord** [comment]
@altavir , thanks for the report.

I personally have very limited experience with Gradle. 

Is it a blocking issue? I mean are you still able to build the project?

**Comment by altavir** [comment]
We've only started to use TANGO, so it is hard to say. For now I just disabled dependecy on `nanocontainer-remoting` and it seems to work without it. Gradle is preferred in modern projects, but the issue is that current `nanocontainer-remoting` is broken and unmaintained, so it is good idea to replace it anyway.
